name: valo_zone
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.16
  animated_bottom_navigation_bar: ^1.3.3
  flutter_screenutil: ^5.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_native_splash: 2.4.0

flutter_native_splash:
  color: "#1B242E"
  image: "assets/icons/ic_Splash_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/characters/
    - assets/characters/characters_card/
    - assets/icons/
    - assets/images/
    - assets/json/

  fonts:
    - family: "Pennypacker"
      fonts:
        - asset: assets/fonts/fonnts.com-Pennypacker_SemiWide_Regular.otf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

